# Generated by Django 3.0.7 on 2020-08-04 19:05

from django.db import migrations
import django_editorjs.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='body',
            field=django_editorjs.fields.EditorJsField(blank=True, null=True),
        ),
    ]
