# Generated by Django 3.0.7 on 2020-08-04 19:12

from django.db import migrations
import editorjs_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_content_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='body',
            field=editorjs_field.fields.EditorJSField(blank=True, null=True),
        ),
    ]
