# Generated by Django 3.0.7 on 2020-08-13 17:40

from django.db import migrations, models
import django.db.models.deletion
import django_editorjs.fields


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_auto_20200813_2040'),
        ('content', '0003_auto_20200804_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='issues.Page', verbose_name='page'),
        ),
        migrations.AlterField(
            model_name='content',
            name='body',
            field=django_editorjs.fields.EditorJsField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='pages',
            field=models.ManyToManyField(blank=True, related_name='content_pages', to='issues.Page', verbose_name='page'),
        ),
    ]
