# Generated by Django 3.0.4 on 2020-04-04 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20200404_1053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ('-pinned', '-added'), 'verbose_name': 'content', 'verbose_name_plural': 'content'},
        ),
    ]
