# Generated by Django 3.0.7 on 2020-08-15 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_auto_20200813_2040'),
        ('content', '0004_auto_20200813_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='issue',
        ),
        migrations.RemoveField(
            model_name='content',
            name='pages',
        ),
        migrations.AlterField(
            model_name='content',
            name='page',
            field=models.ForeignKey(blank=True, help_text='Published on issue / page', null=True, on_delete=django.db.models.deletion.SET_NULL, to='issues.Page', verbose_name='page'),
        ),
    ]
