# Generated by Django 3.0.4 on 2020-05-03 18:47

from django.db import migrations, models
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20200405_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='body',
        ),
        migrations.RemoveField(
            model_name='article',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='video',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='video',
            name='transcript',
        ),
        migrations.AddField(
            model_name='content',
            name='body',
            field=martor.models.MartorField(blank=True, null=True, verbose_name='text body'),
        ),
        migrations.AddField(
            model_name='content',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='summary'),
        ),
    ]
