# Generated by Django 3.0.7 on 2020-08-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_auto_20200813_2040'),
        ('tags', '0001_initial'),
        ('content', '0005_auto_20200815_1635'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='series',
            name='issues',
            field=models.ManyToManyField(blank=True, to='issues.Issue', verbose_name='issue'),
        ),
        migrations.AddField(
            model_name='series',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tags.Tag', verbose_name='tags'),
        ),
    ]
