# Generated by Django 3.0.4 on 2020-05-03 20:39

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20200503_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='body',
            field=mdeditor.fields.MDTextField(blank=True, null=True, verbose_name='text body'),
        ),
    ]
