# Generated by Django 3.0.7 on 2020-08-15 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20200815_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='category',
        ),
        migrations.RemoveField(
            model_name='series',
            name='issues',
        ),
    ]
