# Generated by Django 3.0.4 on 2020-05-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20200503_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='content_set', to='content.Contributor', verbose_name='contributor'),
        ),
    ]
