# Generated by Django 3.0.7 on 2020-09-02 09:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20200816_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='publish_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='publishing time'),
        ),
    ]
