# Generated by Django 3.0.4 on 2020-05-23 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_content_contributors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='contributors',
        ),
    ]
