# Generated by Django 3.0.4 on 2020-05-23 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_remove_content_contributors'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ContentContributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Content', verbose_name='content')),
                ('contribution_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.ContributionType', verbose_name='contribution type')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Contributor', verbose_name='contributor')),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='content_set', through='content.ContentContributor', to='content.Contributor', verbose_name='contributor'),
        ),
    ]
