# Generated by Django 3.1.1 on 2020-09-02 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_auto_20200902_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='body',
        ),
    ]
