# Generated by Django 3.0.4 on 2020-05-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_auto_20200523_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributiontype',
            name='primary',
            field=models.BooleanField(default=False, verbose_name='primary'),
        ),
        migrations.AlterField(
            model_name='contributiontype',
            name='description',
            field=models.CharField(max_length=20, verbose_name='description'),
        ),
    ]
