# Generated by Django 3.1.1 on 2020-09-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_remove_content_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='body',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
