# Generated by Django 3.0.4 on 2020-05-23 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_auto_20200523_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.RemoveField(
            model_name='article',
            name='photo_credits',
        ),
        migrations.RemoveField(
            model_name='video',
            name='guests',
        ),
        migrations.RemoveField(
            model_name='video',
            name='host',
        ),
    ]
