# Generated by Django 3.1.1 on 2020-09-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_content_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='podcast',
        ),
        migrations.AddField(
            model_name='content',
            name='embed_media',
            field=models.TextField(blank=True, null=True, verbose_name='media embed code'),
        ),
    ]
