# Generated by Django 3.0.4 on 2020-05-23 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_auto_20200523_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='issue',
            new_name='issue_x',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='podcast',
            new_name='podcast_x',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='video_url',
            new_name='video_url_x',
        ),
    ]
