# Generated by Django 3.1.1 on 2020-09-21 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0001_initial'),
        ('content', '0013_auto_20200904_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriesContributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.contributiontype', verbose_name='contribution type')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contributors.contributor', verbose_name='contributor')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.series', verbose_name='content')),
            ],
            options={
                'verbose_name': 'content - contributor',
                'verbose_name_plural': 'content - contributors',
            },
        ),
        migrations.AddField(
            model_name='series',
            name='contributors',
            field=models.ManyToManyField(blank=True, through='content.SeriesContributor', to='contributors.Contributor', verbose_name='contributor'),
        ),
    ]
