# Generated by Django 3.0.4 on 2020-05-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_auto_20200523_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='issue',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='podcast',
            field=models.URLField(blank=True, null=True, verbose_name='podcast url'),
        ),
        migrations.AddField(
            model_name='content',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='video url'),
        ),
    ]
