# Generated by Django 3.0.4 on 2020-05-24 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_auto_20200523_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='section title')),
                ('body', models.TextField(blank=True, null=True, verbose_name='section text')),
            ],
            options={
                'verbose_name': 'content section',
                'verbose_name_plural': 'content sections',
                'ordering': ('id',),
            },
        ),
        migrations.AlterModelOptions(
            name='contentcontributor',
            options={'verbose_name': 'content - contributor', 'verbose_name_plural': 'content - contributors'},
        ),
        migrations.AlterModelOptions(
            name='contributiontype',
            options={'ordering': ('id',), 'verbose_name': 'contribution type', 'verbose_name_plural': 'contribution types'},
        ),
        migrations.RemoveField(
            model_name='content',
            name='polymorphic_ctype',
        ),
        migrations.AlterField(
            model_name='content',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='text body'),
        ),
        migrations.CreateModel(
            name='ContentSectionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='content_images/', verbose_name='image')),
                ('content_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.ContentSection', verbose_name='section image')),
            ],
        ),
        migrations.AddField(
            model_name='contentsection',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Content', verbose_name='content'),
        ),
    ]
