# Generated by Django 3.1.1 on 2020-09-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0009_auto_20200918_0020'),
        ('content', '0015_auto_20200921_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='issue',
        ),
        migrations.AddField(
            model_name='series',
            name='issues',
            field=models.ManyToManyField(blank=True, to='issues.Issue', verbose_name='issues'),
        ),
    ]
