# Generated by Django 3.1.1 on 2020-09-28 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
        ('content', '0016_auto_20200921_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='publications.publication', verbose_name='publication'),
        ),
    ]
