# Generated by Django 3.1.1 on 2020-10-05 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publications', '0003_auto_20201005_1326'),
        ('content', '0017_content_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_content', to=settings.AUTH_USER_MODEL, verbose_name='published by'),
        ),
        migrations.AlterField(
            model_name='content',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='published_content', to=settings.AUTH_USER_MODEL, verbose_name='published by'),
        ),
        migrations.AlterField(
            model_name='content',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AlterUniqueTogether(
            name='content',
            unique_together={('slug', 'publication')},
        ),
    ]
