# Generated by Django 3.1.1 on 2020-10-05 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0018_auto_20201005_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_content', to=settings.AUTH_USER_MODEL, verbose_name='added by'),
        ),
        migrations.AlterField(
            model_name='content',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_content', to=settings.AUTH_USER_MODEL, verbose_name='published by'),
        ),
    ]
