# Generated by Django 3.0.4 on 2020-05-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_contentsectionimage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentsectionimage',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='description'),
        ),
    ]
