# Generated by Django 3.1.1 on 2020-10-07 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0010_auto_20201007_2250'),
        ('content', '0019_auto_20201005_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publications.publication', verbose_name='publication'),
        ),
    ]
