# Generated by Django 3.1.1 on 2020-10-11 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_category_publication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='body',
            new_name='data',
        ),
    ]
