# Generated by Django 3.0.4 on 2020-06-07 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_auto_20200524_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentsectionimage',
            options={'ordering': ('id',), 'verbose_name': 'section image', 'verbose_name_plural': 'section images'},
        ),
    ]
