# Generated by Django 3.0.4 on 2020-06-19 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_auto_20200607_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='issue',
        ),
    ]
