# Generated by Django 3.1.1 on 2020-10-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_auto_20201011_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
