# Generated by Django 3.1.2 on 2021-01-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_auto_20201012_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='data',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
    ]
