# Generated by Django 3.0.4 on 2020-06-19 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
        ('content', '0022_remove_content_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='issues.Issue', verbose_name='issue'),
        ),
        migrations.AddField(
            model_name='content',
            name='pages',
            field=models.ManyToManyField(blank=True, to='issues.Page', verbose_name='page'),
        ),
    ]
