# Generated by Django 3.0.4 on 2020-06-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_auto_20200624_1724'),
        ('content', '0023_auto_20200619_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='new_tags',
            field=models.ManyToManyField(blank=True, to='tags.Tag', verbose_name='tags'),
        ),
    ]
