# Generated by Django 3.1.2 on 2021-01-25 20:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0023_auto_20210116_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='content',
            name='added',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='added'),
        ),
    ]
