# Generated by Django 3.1.2 on 2021-01-28 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0025_extrafile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrafile',
            name='file',
            field=models.FileField(upload_to='extra/'),
        ),
    ]
