# Generated by Django 3.0.7 on 2020-06-30 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0025_auto_20200630_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='tags',
        ),
    ]
