# Generated by Django 3.0.7 on 2020-06-30 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0026_remove_content_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='new_tags',
            new_name='tags',
        ),
    ]
