# Generated by Django 3.1.1 on 2020-09-03 06:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('slug', models.SlugField(unique=True)),
                ('editors', models.ManyToManyField(related_name='managed_publications', to=settings.AUTH_USER_MODEL, verbose_name='editors')),
                ('writers', models.ManyToManyField(related_name='contributed_publications', to=settings.AUTH_USER_MODEL, verbose_name='writers')),
            ],
        ),
    ]
