# Generated by Django 3.1.1 on 2020-10-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_publication_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='publications/logo/'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
