# Generated by Django 3.1.1 on 2020-10-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_auto_20201005_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='publications/cover/'),
        ),
    ]
