# Generated by Django 3.1.1 on 2020-10-05 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('publications', '0005_auto_20201005_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='name',
        ),
        migrations.AlterField(
            model_name='publication',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
        ),
    ]
