# Generated by Django 3.1.1 on 2020-10-06 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publications', '0006_auto_20201005_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='editors',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='writers',
        ),
        migrations.AddField(
            model_name='publication',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.site'),
        ),
        migrations.CreateModel(
            name='PublicationUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editor', models.BooleanField(default=False)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.publication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='users',
            field=models.ManyToManyField(blank=True, through='publications.PublicationUser', to=settings.AUTH_USER_MODEL, verbose_name='users'),
        ),
    ]
