# Generated by Django 3.1.1 on 2020-10-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0009_publication_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
