# Generated by Django 3.1.1 on 2020-10-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0010_auto_20201007_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='publications/icon/'),
        ),
        migrations.AddField(
            model_name='publication',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='patreon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='twitter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='youtube',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
