# Generated by Django 3.1.1 on 2020-10-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0011_auto_20201008_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='cover',
        ),
        migrations.AddField(
            model_name='publication',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='about'),
        ),
    ]
