# Generated by Django 3.1.2 on 2021-01-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0012_auto_20201012_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='about_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='about_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
