# Generated by Django 3.1.2 on 2021-01-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0013_auto_20210116_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='analytics_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
