# Generated by Django 3.0.4 on 2020-03-11 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_auto_20200311_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='video',
            field=models.URLField(blank=True, null=True, verbose_name='Video'),
        ),
        migrations.AddField(
            model_name='contributor',
            name='instagram',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contributor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='contributor/'),
        ),
        migrations.AddField(
            model_name='contributor',
            name='twitter',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
