# Generated by Django 3.0.4 on 2020-03-11 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_auto_20200311_1221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-added',), 'verbose_name': 'article', 'verbose_name_plural': 'articles'},
        ),
    ]
