# Generated by Django 3.0.4 on 2020-03-12 09:43

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_auto_20200311_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
    ]
