# Generated by Django 3.0.4 on 2020-03-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_auto_20200313_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='issue',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
