# Generated by Django 3.0.4 on 2020-03-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_article_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='related_articles',
            field=models.ManyToManyField(blank=True, related_name='_article_related_articles_+', to='articles.Article'),
        ),
    ]
