# Generated by Django 3.0.4 on 2020-04-01 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0022_auto_20200331_1624'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Contributor',
        ),
        migrations.DeleteModel(
            name='Series',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
