# Generated by Django 3.1.2 on 2021-04-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Etkinlik', 'verbose_name_plural': 'Etkinlikler'},
        ),
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(blank=True, help_text="Online etkinlikler için toplantı URL'i", max_length=400, null=True, verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Tanım'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bitiş'),
        ),
        migrations.AlterField(
            model_name='event',
            name='link',
            field=models.URLField(blank=True, help_text='Detaylı bilgi için bağlantı', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(verbose_name='Başlangıç'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Başlık'),
        ),
    ]
