# Generated by Django 3.1.2 on 2021-04-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20210410_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Tip'),
        ),
    ]
