# Generated by Django 3.1.2 on 2021-04-10 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20210410_1945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventtype',
            options={'verbose_name': 'Etkinlik tipi', 'verbose_name_plural': 'Etkinlik tipleri'},
        ),
    ]
