# Generated by Django 3.0.4 on 2020-06-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200607_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=250, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='itemalternative',
            name='description',
            field=models.CharField(max_length=250, verbose_name='description'),
        ),
    ]
