# Generated by Django 3.0.4 on 2020-06-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200607_1524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemalternative',
            options={'verbose_name': 'alternative', 'verbose_name_plural': 'alternatives'},
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='x', editable=False, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
