# Generated by Django 3.0.4 on 2020-05-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'subscription', 'verbose_name_plural': 'subscriptions'},
        ),
        migrations.AlterField(
            model_name='subscription',
            name='type',
            field=models.CharField(choices=[('dijital', "Dijital abonelik - 50 TL (Solfasol'unuz her ay elektronik posta kutunuzda!)"), ('yillik', "Yıllık abonelik - 100 TL (Solfasol'unuz her ay adresinize posta yoluyla ulaştırılır!)"), ('destekci', "Destekçi abonelik - 200 TL (Solfasol'un Ankara'nın farklı kesimlerine ulaşmasına destek olun! Ayrıca Solfasol Ankara Gezilerinde misafirimiz olun."), ('yurtdisi', 'Yurtdışı abonelik - 200 TL (Uzaktayım demeyin, Solfasol dünyanın her yerine ulaşıyor!)')], default='destekci', max_length=10, verbose_name='Abonelik türü'),
        ),
    ]
