# Generated by Django 3.0.4 on 2020-06-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20200511_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='type',
            field=models.CharField(choices=[('dijital', 'Dijital abonelik - 50 TL (Solfasol her ay elektronik posta kutunuzda!)'), ('yillik', 'Yıllık abonelik - 100 TL (Solfasol her ay adresinize posta yoluyla ulaştırılır!)'), ('destekci', 'Destekçi abonelik - 200 TL (Hem daha çok kişiye ulaşmaımıza yardımcı olun hem de Solfasol Ankara Gezilerinde misafirimiz olun!)'), ('yurtdisi', 'Yurtdışı abonelik - 200 TL (Uzaktayım demeyin, Solfasol dünyanın her yerine ulaşıyor!)')], default='destekci', max_length=10, verbose_name='Abonelik türü'),
        ),
    ]
