# Generated by Django 3.0.7 on 2020-07-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_auto_20200619_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='renewal',
            field=models.BooleanField(default=False, verbose_name='renewal'),
        ),
    ]
