# Generated by Django 3.1.2 on 2021-02-13 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_auto_20210213_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='sub_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.subscriptiontype'),
        ),
    ]
