# Generated by Django 3.1.2 on 2021-02-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_subscription_sub_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontype',
            name='postal_address_required',
            field=models.BooleanField(default=True),
        ),
    ]
