# Generated by Django 3.1.2 on 2021-02-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_subscriptiontype_postal_address_required'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptiontype',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='subscriptiontype',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscriptiontype',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
