# Generated by Django 3.1.2 on 2021-02-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_auto_20210213_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptiontype',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
