# Generated by Django 3.1.2 on 2021-04-02 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_auto_20210213_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='type',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='sub_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.subscriptiontype', verbose_name='Abonelik tipi'),
        ),
    ]
