# Generated by Django 3.1.2 on 2021-04-05 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_auto_20210402_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='subscriptions.subscriptiontype', verbose_name='Abonelik tipi'),
        ),
    ]
