# Generated by Django 3.0.7 on 2020-07-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='name')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('embed_url', models.URLField()),
            ],
            options={
                'verbose_name': 'feedback form',
                'verbose_name_plural': 'feedback forms',
            },
        ),
    ]
