# Generated by Django 3.0.4 on 2020-06-19 09:18

from django.db import migrations, models
import django.db.models.deletion
import solfasol.issues.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='number')),
                ('date', models.DateField()),
                ('cover', models.ImageField(upload_to='x', verbose_name='cover')),
                ('pdf', models.FileField(upload_to='x', verbose_name='PDF')),
                ('page_count', models.PositiveSmallIntegerField(verbose_name='page count')),
            ],
            options={
                'verbose_name': 'issue',
                'verbose_name_plural': 'issues',
                'ordering': ('-number',),
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='number')),
                ('pdf', models.FileField(upload_to='x', verbose_name='PDF')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issues.Issue', verbose_name='issue')),
            ],
        ),
        migrations.CreateModel(
            name='IssueTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issues.Issue', verbose_name='issue')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.Tag', verbose_name='tag')),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='tags',
            field=models.ManyToManyField(through='issues.IssueTag', to='tags.Tag', verbose_name='tags'),
        ),
    ]
