# Generated by Django 3.0.4 on 2020-06-24 14:24

from django.db import migrations, models
import solfasol.issues.models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_auto_20200624_1724'),
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='x', verbose_name='cover'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='page_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='page count'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='x', verbose_name='PDF'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='tags',
            field=models.ManyToManyField(blank=True, through='issues.IssueTag', to='tags.Tag', verbose_name='tags'),
        ),
    ]
