# Generated by Django 3.0.7 on 2020-08-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_auto_20200725_1205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ('issue', 'number'), 'verbose_name': 'page', 'verbose_name_plural': 'pages'},
        ),
        migrations.AlterField(
            model_name='page',
            name='number',
            field=models.PositiveIntegerField(verbose_name='page number'),
        ),
    ]
