# Generated by Django 3.0.4 on 2020-06-25 05:54

from django.db import migrations, models
import solfasol.issues.models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_auto_20200624_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=solfasol.issues.models.page_image_path, verbose_name='PDF'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=solfasol.issues.models.issue_cover_image_path, verbose_name='cover'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=solfasol.issues.models.issue_pdf_path, verbose_name='PDF'),
        ),
        migrations.AlterField(
            model_name='page',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='x', verbose_name='PDF'),
        ),
    ]
