# Generated by Django 3.0.4 on 2020-06-25 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_auto_20200625_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='page',
            name='pdf',
        ),
        migrations.DeleteModel(
            name='IssueTag',
        ),
    ]
