# Generated by Django 3.0.4 on 2020-06-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_auto_20200624_1724'),
        ('issues', '0004_auto_20200625_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tags.Tag', verbose_name='tags'),
        ),
    ]
