# Generated by Django 3.0.7 on 2020-08-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_remove_page_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='page_data',
            field=models.TextField(blank=True, help_text='temporary page data for creating pages remotely', null=True, verbose_name='page data'),
        ),
    ]
