# Generated by Django 3.1.1 on 2020-09-17 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_issue_page_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='page_data',
        ),
    ]
