# Generated by Django 3.0.4 on 2020-06-25 10:54

from django.db import migrations, models
import solfasol.issues.models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_auto_20200624_1724'),
        ('issues', '0005_issue_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tags.Tag', verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=solfasol.issues.models.page_image_path, verbose_name='image'),
        ),
    ]
