# Generated by Django 3.0.7 on 2020-07-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0006_auto_20200625_1354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ('-year', '-month'), 'verbose_name': 'issue', 'verbose_name_plural': 'issues'},
        ),
        migrations.RemoveField(
            model_name='issue',
            name='date',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='number',
        ),
        migrations.AddField(
            model_name='issue',
            name='month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Jan'), (2, 'Feb'), (3, 'Mar'), (4, 'Apr'), (5, 'May'), (6, 'Jun'), (7, 'Jul'), (8, 'Aug'), (9, 'Sep'), (10, 'Oct'), (11, 'Nov'), (12, 'Dec')], default=1, verbose_name='month'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='name',
            field=models.CharField(default='?', max_length=50, verbose_name='name / number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='year',
            field=models.PositiveSmallIntegerField(choices=[(2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019)], default=2011, verbose_name='year'),
            preserve_default=False,
        ),
    ]
