# Generated by Django 3.1.1 on 2020-09-17 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0006_remove_issue_page_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='file_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
