# Generated by Django 3.1.1 on 2020-09-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0007_issue_file_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='file_data',
            field=models.TextField(blank=True, help_text='file data for creating pages remotely', null=True),
        ),
    ]
