# Generated by Django 3.0.4 on 2020-06-24 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='related_tags',
            field=models.ManyToManyField(blank=True, related_name='_tag_related_tags_+', to='tags.Tag', verbose_name='related tags'),
        ),
        migrations.CreateModel(
            name='TagVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='video url')),
                ('description', models.CharField(blank=True, max_length=280, null=True, verbose_name='description')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('publish', models.BooleanField(default=True)),
                ('contributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contributors.Contributor', verbose_name='contributor')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.Tag', verbose_name='tag')),
            ],
            options={
                'verbose_name': 'tag video',
                'verbose_name_plural': 'tag videos',
            },
        ),
        migrations.CreateModel(
            name='TagImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tags/', verbose_name='image')),
                ('description', models.CharField(blank=True, max_length=280, null=True, verbose_name='description')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('publish', models.BooleanField(default=True)),
                ('contributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contributors.Contributor', verbose_name='contributor')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.Tag', verbose_name='tag')),
            ],
            options={
                'verbose_name': 'tag image',
                'verbose_name_plural': 'tag images',
            },
        ),
        migrations.CreateModel(
            name='TagDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.TextField(verbose_name='definition')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('publish', models.BooleanField(default=True)),
                ('contributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contributors.Contributor', verbose_name='contributor')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.Tag', verbose_name='tag')),
            ],
            options={
                'verbose_name': 'tag definition',
                'verbose_name_plural': 'tag definitions',
            },
        ),
    ]
